//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStockDetail()
        {
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StockId { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string IsDeleted { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        public virtual tblStock tblStock { get; set; }
    }
}
