//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamEmployee
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public int TeamEmployeeId { get; set; }
        public Nullable<decimal> TeamEmployeeBudget { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
